// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2frVu-LTI7vL6S6gP41WZllrxlhuZss0',
    appId: '1:378283287142:web:b7e8b6d1f7b364cbe3c3a7',
    messagingSenderId: '378283287142',
    projectId: 'broke-game-28abd',
    authDomain: 'broke-game-28abd.firebaseapp.com',
    storageBucket: 'broke-game-28abd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZuP0UTC8SqZjpJDGCWAI-NzUj0vhXsX0',
    appId: '1:378283287142:android:3bdd23f16dc27ab2e3c3a7',
    messagingSenderId: '378283287142',
    projectId: 'broke-game-28abd',
    storageBucket: 'broke-game-28abd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAid02xCH0P7TBYZ4Z140I5ulRDAQNjfkA',
    appId: '1:378283287142:ios:79093f8cf2cc11b3e3c3a7',
    messagingSenderId: '378283287142',
    projectId: 'broke-game-28abd',
    storageBucket: 'broke-game-28abd.firebasestorage.app',
    iosBundleId: 'com.example.brokeGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAid02xCH0P7TBYZ4Z140I5ulRDAQNjfkA',
    appId: '1:378283287142:ios:79093f8cf2cc11b3e3c3a7',
    messagingSenderId: '378283287142',
    projectId: 'broke-game-28abd',
    storageBucket: 'broke-game-28abd.firebasestorage.app',
    iosBundleId: 'com.example.brokeGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2frVu-LTI7vL6S6gP41WZllrxlhuZss0',
    appId: '1:378283287142:web:7b487389175f834ee3c3a7',
    messagingSenderId: '378283287142',
    projectId: 'broke-game-28abd',
    authDomain: 'broke-game-28abd.firebaseapp.com',
    storageBucket: 'broke-game-28abd.firebasestorage.app',
  );
}
